server:
  port: 7070
  servlet:
    context-path: /
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      probes.enabled: true
      livenessState.enabled: true
      readinessState.enabled: true
      show-details: always
#  server:
#    port: 7072

grpc:
  server:
    port: 7071